main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.21.1"
author: sstock2005
description: A playtime limiter plugin for Minecraft
commands:
  ptl:
    description: Playtime Limiter Help Command
    usage: "For a list of commands, type /ptl help"
    aliases: h
permissions:
  example.*:
    description: Grants all other permissions
    default: false
    children:
      example.test: true